# Generated by Django 4.2.27 on 2026-03-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signal',
            name='step_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.stepexecution'),
        ),
        migrations.AlterField(
            model_name='stepexecution',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='core.step'),
        ),
    ]
